name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets: inherit
    with:
      provider: machine

  terraform-deploy-tests:
    name: Run terraform deployment tests
    uses: canonical/observability/.github/workflows/run-tox-environment.yaml@v1
    with:
      tox-env-name: terraform-deploy
      run-on: "[self-hosted, amd64]"
      prepare-host-env: true
      provider: machine
      extra-snaps: terraform
    secrets: inherit
